services:
  gateway:
    build:
      context: ./gateway 
    ports:
      - "8000:8000" 
    environment:
      - DEBUG=1
    networks:
      - techops-network

  user-service:
    build:
      context: ./user_service
    environment:
      - DEBUG=1
    depends_on:
      db-user-service:
        condition: service_healthy
    networks:
      - techops-network

  blog-service:
    build:
      context: ./blog_service
    environment:
      - DEBUG=1
    depends_on:
      db-blog-service:
        condition: service_healthy
    networks:
      - techops-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true

  db-user-service:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    container_name: db-user-service
    networks:
      - techops-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user", "-d", "mydatabase"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  db-blog-service:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    container_name: db-blog-service
    networks:
      - techops-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user", "-d", "mydatabase"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

networks:
  techops-network:
