services:
  gateway:
    build:
      context: ./gateway 
    volumes:
      - ./gateway:/app 
    ports:
      - "8000:8000" 
    environment:
      - DEBUG=1
    networks:
      - techops-network

  user-service:
    build:
      context: ./user_service
    volumes:
      - ./user_service:/app
    environment:
      - DEBUG=1
    depends_on:
      - db-user-service
    networks:
      - techops-network

  blog-service:
    build:
      context: ./blog_service
    volumes:
      - ./blog_service:/app
    environment:
      - DEBUG=1
    depends_on:
      - db-blog-service
    networks:
      - techops-network

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true

  db-user-service:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    container_name: db-user-service
    networks:
      - techops-network

  db-blog-service:
    image: postgres:15
    volumes:
      - blog_service_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    container_name: db-blog-service
    networks:
      - techops-network

volumes:
  postgres_data:
  blog_service_data:

networks:
    techops-network: