version: '3.8'

services:
  backend:
    build:
      context: ./backend  # Path to the Django Dockerfile
    volumes:
      - ./backend:/app  # Bind mount for live reload
    ports:
      - "8000:8000"  # Expose Django on port 8000
    environment:
      - DEBUG=1
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend  # Path to the React Dockerfile
    volumes:
      - ./frontend:/app  # Bind mount for live reload
      - /app/node_modules  # Prevent overwriting node_modules
    ports:
      - "3000:3000"  # Expose React on port 3000
    environment:
      - CHOKIDAR_USEPOLLING=true  # Fix for file system watching in Docker

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase

volumes:
  postgres_data:
