# Generated by Django 4.2 on 2024-12-25 17:38

from django.db import migrations


class Migration(migrations.Migration):

  dependencies = [
      ('myapp', '0001_create_user_table'),
  ]

  operations = [
      migrations.RemoveField(
          model_name='user',
          name='salt',
      ),
  ]
