# Generated by Django 4.2 on 2024-12-23 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

  dependencies = [
      ("myapp", "0001_create_blog_table"),
  ]

  operations = [
      migrations.AlterField(
          model_name="blog",
          name="content",
          field=models.CharField(max_length=12000),
      ),
      migrations.AlterField(
          model_name="blog",
          name="title",
          field=models.CharField(max_length=300),
      ),
  ]
