# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/blog_service.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'proto/blog_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18proto/blog_service.proto\"E\n\x11\x43reateBlogRequest\x12\x10\n\x08writerId\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\"F\n\x12\x43reateBlogResponse\x12\x11\n\tisSuccess\x18\x01 \x01(\x08\x12\x10\n\x08\x65rrorMsg\x18\x02 \x01(\t\x12\x0b\n\x03url\x18\x03 \x01(\t2D\n\x0b\x42logService\x12\x35\n\nCreateBlog\x12\x12.CreateBlogRequest\x1a\x13.CreateBlogResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.blog_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATEBLOGREQUEST']._serialized_start=28
  _globals['_CREATEBLOGREQUEST']._serialized_end=97
  _globals['_CREATEBLOGRESPONSE']._serialized_start=99
  _globals['_CREATEBLOGRESPONSE']._serialized_end=169
  _globals['_BLOGSERVICE']._serialized_start=171
  _globals['_BLOGSERVICE']._serialized_end=239
# @@protoc_insertion_point(module_scope)
