# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import blog_service_pb2 as proto_dot_blog__service__pb2

GRPC_GENERATED_VERSION = "1.68.1"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
  from grpc._utilities import first_version_is_lower

  _version_not_supported = first_version_is_lower(
      GRPC_VERSION, GRPC_GENERATED_VERSION
  )
except ImportError:
  _version_not_supported = True

if _version_not_supported:
  raise RuntimeError(
      f"The grpc package installed is at version {GRPC_VERSION},"
      + f" but the generated code in proto/blog_service_pb2_grpc.py depends on"
      + f" grpcio>={GRPC_GENERATED_VERSION}."
      + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
      +
        f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
  )


class BlogServiceStub(object):
  """Missing associated documentation comment in .proto file."""

  def __init__(self, channel):
    """Constructor.

    Args:
        channel: A grpc.Channel.
    """
    self.CreateBlog = channel.unary_unary(
        "/BlogService/CreateBlog",
        request_serializer=proto_dot_blog__service__pb2.CreateBlogRequest.SerializeToString,
        response_deserializer=proto_dot_blog__service__pb2.CreateBlogResponse.FromString,
        _registered_method=True,
    )
    self.GetBlogDetail = channel.unary_unary(
        "/BlogService/GetBlogDetail",
        request_serializer=proto_dot_blog__service__pb2.GetBlogDetailRequest.SerializeToString,
        response_deserializer=proto_dot_blog__service__pb2.GetBlogDetailResponse.FromString,
        _registered_method=True,
    )
    self.GetBlogList = channel.unary_unary(
        "/BlogService/GetBlogList",
        request_serializer=proto_dot_blog__service__pb2.GetBlogListRequest.SerializeToString,
        response_deserializer=proto_dot_blog__service__pb2.GetBlogListResponse.FromString,
        _registered_method=True,
    )


class BlogServiceServicer(object):
  """Missing associated documentation comment in .proto file."""

  def CreateBlog(self, request, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details("Method not implemented!")
    raise NotImplementedError("Method not implemented!")

  def GetBlogDetail(self, request, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details("Method not implemented!")
    raise NotImplementedError("Method not implemented!")

  def GetBlogList(self, request, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details("Method not implemented!")
    raise NotImplementedError("Method not implemented!")


def add_BlogServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      "CreateBlog": grpc.unary_unary_rpc_method_handler(
          servicer.CreateBlog,
          request_deserializer=proto_dot_blog__service__pb2.CreateBlogRequest.FromString,
          response_serializer=proto_dot_blog__service__pb2.CreateBlogResponse.SerializeToString,
      ),
      "GetBlogDetail": grpc.unary_unary_rpc_method_handler(
          servicer.GetBlogDetail,
          request_deserializer=proto_dot_blog__service__pb2.GetBlogDetailRequest.FromString,
          response_serializer=proto_dot_blog__service__pb2.GetBlogDetailResponse.SerializeToString,
      ),
      "GetBlogList": grpc.unary_unary_rpc_method_handler(
          servicer.GetBlogList,
          request_deserializer=proto_dot_blog__service__pb2.GetBlogListRequest.FromString,
          response_serializer=proto_dot_blog__service__pb2.GetBlogListResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      "BlogService", rpc_method_handlers
  )
  server.add_generic_rpc_handlers((generic_handler,))
  server.add_registered_method_handlers("BlogService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class BlogService(object):
  """Missing associated documentation comment in .proto file."""

  @staticmethod
  def CreateBlog(
      request,
      target,
      options=(),
      channel_credentials=None,
      call_credentials=None,
      insecure=False,
      compression=None,
      wait_for_ready=None,
      timeout=None,
      metadata=None,
  ):
    return grpc.experimental.unary_unary(
        request,
        target,
        "/BlogService/CreateBlog",
        proto_dot_blog__service__pb2.CreateBlogRequest.SerializeToString,
        proto_dot_blog__service__pb2.CreateBlogResponse.FromString,
        options,
        channel_credentials,
        insecure,
        call_credentials,
        compression,
        wait_for_ready,
        timeout,
        metadata,
        _registered_method=True,
    )

  @staticmethod
  def GetBlogDetail(
      request,
      target,
      options=(),
      channel_credentials=None,
      call_credentials=None,
      insecure=False,
      compression=None,
      wait_for_ready=None,
      timeout=None,
      metadata=None,
  ):
    return grpc.experimental.unary_unary(
        request,
        target,
        "/BlogService/GetBlogDetail",
        proto_dot_blog__service__pb2.GetBlogDetailRequest.SerializeToString,
        proto_dot_blog__service__pb2.GetBlogDetailResponse.FromString,
        options,
        channel_credentials,
        insecure,
        call_credentials,
        compression,
        wait_for_ready,
        timeout,
        metadata,
        _registered_method=True,
    )

  @staticmethod
  def GetBlogList(
      request,
      target,
      options=(),
      channel_credentials=None,
      call_credentials=None,
      insecure=False,
      compression=None,
      wait_for_ready=None,
      timeout=None,
      metadata=None,
  ):
    return grpc.experimental.unary_unary(
        request,
        target,
        "/BlogService/GetBlogList",
        proto_dot_blog__service__pb2.GetBlogListRequest.SerializeToString,
        proto_dot_blog__service__pb2.GetBlogListResponse.FromString,
        options,
        channel_credentials,
        insecure,
        call_credentials,
        compression,
        wait_for_ready,
        timeout,
        metadata,
        _registered_method=True,
    )
